<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title><?php echo $__config->site['name']; ?></title>

		<link rel="icon" type="image/x-icon" href="/favicon.ico" />
		<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />

		<link rel="stylesheet" href="<?php echo $__dynamic->css('/css/bootstrap.css'); ?>" />
		<link rel="stylesheet" href="<?php echo $__dynamic->css('/css/foundation.css'); ?>" />
		<link rel="stylesheet" href="<?php echo $__dynamic->css('/css/core.css'); ?>" />

		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', '<?php // TODO ?>']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container<?php $__fluid ? '-fluid' : ''; ?>">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="/"><?php echo $__config->site['name']; ?></a>
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li class="active"><a href="/">Home</a></li>
							<li><a href="/about">About</a></li>
							<li><a href="/contact">Contact</a></li>
						</ul>
						<ul class="nav pull-right">
							<li><a href="/login"><span class="icon-lock icon-white"></span> Sign in / Sign up</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div class="container<?php $__fluid ? '-fluid' : ''; ?>">
			<div class="content <?php echo $__css_class; ?>">
				<?php require $__template; ?>
			</div>
			<hr />
			<footer>
				<p>&copy; <?php echo date('Y') . ' ' . $__config->site['name']; ?></p>
			</footer>
		</div>

		<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js"></script>
		<script src="<?php echo $__dynamic->js('/js/bootstrap.js'); ?>"></script>
		<script src="<?php echo $__dynamic->js('/js/pickles.js'); ?>"></script>
		<script src="<?php echo $__dynamic->js('/js/core.js'); ?>"></script>

		<script>
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', '<?php echo $__config->site['analytics']; ?>']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</body>
</html>
