language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - master
    - 2.0
    - 1.9

services:
  - memcache
  - memcached
  - redis

install:
  - composer self-update
  - composer install

before_script:
  - ./tests/travis.sh
  - mysql -e "create database IF NOT EXISTS test;" -u root
  - mysql test < tests/schema.sql -u root
  - mkdir -p build/logs
  - phpenv rehash

script:
  - phpunit --coverage-clover /home/travis/build/joshtronic/pickles/build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls --config ../.coveralls.yml -v
