language: php

php:
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis

install:
  - composer install
  - cd vendors/php-test-helpers
  - phpize
  - ./configure --enable-test-helpers
  - make
  - sudo make install
  - cd ../../

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension = test_helpers.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - mkdir -p vendors/build/logs

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/pickles/vendors/build/logs/clover.xml --bootstrap ./tests/bootstrap.php ./tests

after_success:
  - php vendors/composer/bin/coveralls --config ../.coveralls.yml -v
