language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  only:
    - master

services:
  - memcache
  - memcached
  - redis

install:
  - composer install
  - pecl install uopz

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo -e "zend_$(cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini)" > ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension = /home/travis/.phpenv/versions/$(php -r 'echo phpversion();')/lib/php/extensions/no-debug-zts-20100525/uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "[uopz]" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "uopz.overloads=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e "create database IF NOT EXISTS test;" -u root
  - mysql test < tests/schema.sql -u root
  - mkdir -p build/logs

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/pickles/build/logs/clover.xml --bootstrap ./tests/bootstrap.php ./tests

after_success:
  - php vendor/bin/coveralls --config ../.coveralls.yml -v
