language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - memcache
  - memcached
  - redis

install:
  - composer install
  - mkdir vendor/php-test-helpers
  - git clone git@github.com:php-test-helpers/php-test-helpers.git /tmp/php-test-helpers
  - cd vendor/php-test-helpers
  - phpize
  - ./configure --enable-test-helpers
  - make
  - sudo make install
  - cd -

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "zend_extension = /home/travis/build/joshtronic/pickles/vendor/php-test-helpers/modules/test_helpers.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - mysql test < tests/schema.sql
  - mkdir -p vendor/build/logs

script:
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/pickles/vendor/build/logs/clover.xml --bootstrap ./tests/bootstrap.php ./tests

after_success:
  - php vendor/composer/bin/coveralls --config ../.coveralls.yml -v
