language: php

php:
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install
  - pear channel-discover pear.phpunit.de
  - pecl install phpunit/test_helpers

script:
  - mkdir -p vendors/build/logs
  - phpunit --colors --coverage-clover /home/travis/build/joshtronic/pickles/vendors/build/logs/clover.xml --bootstrap ./tests/bootstrap.php ./tests

after_script:
  - php vendors/composer/bin/coveralls --config ../.coveralls.yml -v
