language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm
    - php: hhvm-nightly

branches:
  only:
    - master

services:
  - memcache
  - memcached
  - redis

install:
  - composer install

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e "create database IF NOT EXISTS test;" -u root
  - mysql test < tests/schema.sql -u root
  - mkdir -p build/logs
  - phpenv rehash

script:
  - phpunit --coverage-clover /home/travis/build/joshtronic/pickles/build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls --config ../.coveralls.yml -v
