language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.3
    - php: hhvm

install:
  - composer install

script: phpunit --bootstrap ./tests/bootstrap.php ./tests
