<!DOCTYPE html>
<html>
	<head>
		<title>Sample PICKLES Site</title>
		<!-- The following line includes the jQuery file in /path/to/pickles/js -->
		<script type="text/javascript" src="<?php echo $__dynamic->js('/__pickles/js/jquery.js'); ?>"></script>
	</head>
	<body>
		<h1>PICKLES Sample Site</h1>
		<h2>Super simple example of PICKLES in action</h2>
		<?php
		// Loads the module's template
		require_once $__template;
		?>
	</body>
</html>
